openapi: 3.0.3
info:
  title: Auth API (001-email-auth)
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: Authenticate user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Successful authentication (sets session cookie)
        '401':
          description: Generic authentication failure (do not reveal whether email exists)
  /api/auth/request-reset:
    post:
      summary: Request password reset via email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required: [email]
      responses:
        '200':
          description: Reset request processed (generic response)
  /api/auth/reset:
    post:
      summary: Complete password reset using token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
              required: [token, newPassword]
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Invalid or expired token
  /api/admin/invite:
    post:
      summary: Admin invites a new user (sends invitation email)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required: [email]
      responses:
        '200':
          description: Invitation queued
  /api/admin/users:
    get:
      summary: List users (admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User list
    post:
      summary: Create user (admin) — may trigger invitation flow
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                role:
                  type: string
              required: [email]
      responses:
        '201':
          description: User created / invitation sent
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
